# Generated by Django 5.2.2 on 2025-10-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0002_staffprofile_created_at_staffprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
